language: php

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER: max[self]=0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.2
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.3
    - php: 7.4

php:
  - 7.2

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi
  - if [ "$TWILIO_VERSION" != "" ]; then composer require --dev --no-update twilio/sdk=$TWILIO_VERSION; fi

install: composer update $COMPOSER_FLAGS --prefer-dist

script: phpunit
