language: php

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER: weak

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.0
      env: SYMFONY_VERSION='3.0.*'

php:
  - 7.0
  - 7.1

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi

install: composer update $COMPOSER_FLAGS --prefer-dist

script: if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then phpunit --coverage-clover=coverage.clover; else phpunit; fi
